### ISSUE TITLE
Dataset Request for Bangla-spam-sms classification 

### ISSUE THREAD

**Issue by syeed111** [KawshikKumar/Multilingual-SMS-Text-Classification#1]
We are doing research on building a model for bangla-spam-sms classification  which will be mobile friendly . We've got only one dataset on kaggle which has a few bangla sms . We will appriciate if you share your dataset through kaggle or directly  to help us building a strong model . Thanks for your support .

**Comment by syeed111** [comment]
@KawshikKumar  is the dataset available ?

**Comment by JibonMallick** [comment]
@KawshikKumar please give me dataset.

**Comment by KawshikKumar** [comment]
Hello, the dataset can not be shared because a portion of the dataset contains private data. The dataset was created by combining other datasets that are available online. Please check the References section of the paper to access the rest of the dataset that were used.
